version: '3'


volumes:
  postgres_volume:

services:
  pg_music:
    image: postgres:14-alpine3.17
    container_name: cl-psql
    ports:
      - "${PG_PORT}:5432"
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  migrator_pg:
    container_name: cl-psqlMigrator
    build:
      context: .
      dockerfile: migrations.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg_music